# Generated by Django 3.0.4 on 2020-09-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locUnits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locunit',
            name='last_15_days',
        ),
        migrations.RemoveField(
            model_name='locunit',
            name='last_30_days',
        ),
        migrations.RemoveField(
            model_name='locunit',
            name='last_45_days',
        ),
        migrations.AddField(
            model_name='locunit',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
